# Spring settings
spring:
  profiles:
    active: dev

# Huawei Cloud settings
huawei:
  sms:
    apiHost: https://api.rtc.huaweicloud.com:10443
    accessKey: ${HUAWEI_SMS_ACCESS_KEY}
    accessSecretKey: ${HUAWEI_SMS_ACCESS_SECRET_KEY}
    callBackUrl: ${HUAWEI_SMS_CALLBACK_URL:}
    signature: ${HUAWEI_SMS_SIGNATURE:华为云短信测试}
    test:
      number: 13400000000
      bizId: 000000000000000000^0
