# Spring settings
spring:
  profiles:
    active: dev

# Huawei Cloud settings
huawei:
  sms:
    apiHost: https://api.rtc.huaweicloud.com:10443
    accessKey: ${HUAWEI_OBS_ACCESS_KEY}
    accessSecretKey: ${HUAWEI_OBS_ACCESS_SECRET_KEY}
    test:
      number: 13400000000
      bizId: 000000000000000000^0
